### ISSUE TITLE
 call() missing 2 required positional arguments: 'environ' and 'start_response'

### ISSUE THREAD

**Issue by sunmouren** [rahmonov/alcazar#5]
web_1  | [2020-07-02 09:32:45 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_1  | [2020-07-02 09:32:45 +0000] [1] [INFO] Listening at: http://127.0.0.1:8000 (1)
web_1  | [2020-07-02 09:32:45 +0000] [1] [INFO] Using worker: sync
web_1  | [2020-07-02 09:32:45 +0000] [7] [INFO] Booting worker with pid: 7
web_1  | [2020-07-02 09:32:45 +0000] [7] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
web_1  |     mod = importlib.import_module(module)
web_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1  |   File "/usr/src/app/code/app.py", line 5, in <module>
web_1  |     app()
web_1  | TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response'
web_1  | [2020-07-02 09:32:45 +0000] [7] [INFO] Worker exiting (pid: 7)
web_1  | [2020-07-02 09:32:45 +0000] [1] [INFO] Shutting down: Master
web_1  | [2020-07-02 09:32:45 +0000] [1] [INFO] Reason: Worker failed to boot.
building_own_python_web_framework_web_1 exited with code 3

**Comment by nixfreak** [comment]
Can you check your api code for syntax errors or mispellings like "**reponse**, instead of "**_response_**")
